### ISSUE TITLE
deploy application on heroku

### ISSUE THREAD

**Issue by nancy-binani** [nancy-binani/wheel#22]
Deployed at https://nancyneetouichallenge.herokuapp.com
Credentials:-
Username : oliver@example.com
Password : welcome

Please review.

**Comment by yedhink** [comment]
@nancy-binani https://github.com/nancy-binani/wheel/pull/23#issuecomment-1260592354

**Comment by nancy-binani** [comment]
Fixed according to your reviews.

**Comment by yedhink** [comment]
@nancy-binani I am not sure why you've reopened this issue.

I had already mentioned that you can continue with the next task. Please go ahead with the same.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/31244999/192769574-b1a801be-63dc-4b36-9419-567599f7bbaa.png">

**Comment by nancy-binani** [comment]
I am already working on another task. I just got confused whether I should close it now or after getting the reply or reaction from you after fixing the changes.
